[control_plane]
cks-control-plane ansible_host=192.168.252.3 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/cks_lab_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[arch_laptop]
192.168.1.160

[arch_laptop:vars]
ansible_user=defiant
# These link directly to the encrypted Vault variables we will create next
ansible_password="{{ arch_login_password }}"
ansible_sudo_pass="{{ arch_sudo_password }}"